### ISSUE TITLE
mRo X2.1 no control input on APM Planner screen. 

### ISSUE THREAD

**Issue by H571531** [mRoboticsIO/Hardware#1]
While setting up a mRo Nano Talon we have come upon a problem. There is no input signals from the RX on the configure radio screen. Attempting to go into calibration apm-planner gives the: "Radio Control is not active or turned on" error. We have tested that the reciever is outputting signals on all pins. 

Let me know what kind of files/logs are needed.

We have updated the firmware of the flightcontroller (x2.1) with the firmware given on: https://docs.px4.io/en/flight_controller/mro_x2.1.html

**Comment by tops4u** [comment]
Do not confuse PX4 and Arducopter. APM Planer works for Arducopter only, while the Link you refer to is for the PX4 Firmware which uses QGC (QGroundControl). Also all Pixhawk Controllers require SBus or PPM Sum signals, single PWM Signals can not be connected directly to the HW. 
Despite: such questions or issues should be posted in the respective Firmware development Project Arducopter or PX4 as this is most likely not Pixracer HW related.

**Comment by H571531** [comment]
Thank you! Sorry for raising the issue on the wrong git. It seemed natural to post it in the git for the actual product. 
 
I will attempt to use QGC and retry sbus.
